{% set name = "sparkmagic" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-incubator/sparkmagic/archive/{{ version }}.tar.gz
  sha256: d2c602744b43bd5c07a8e99129444e38413d065d5621c1fdd518af64dd05a880

build:
  number: 0
  noarch: python
  script: cd sparkmagic && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - autovizwidget >=0.6
    - hdijupyterutils >=0.6
    - ipykernel
    - ipython >=4.0.2
    - ipywidgets >5.0.0
    - notebook >=4.2
    - numpy
    - pandas >=0.17.1
    - python >=3.6
    - requests
    - requests-kerberos >=0.8.0
    - tornado >=4

test:
  requires:
    - pip
  imports:
    - sparkmagic
  commands:
    - pip check || true

about:
  home: https://github.com/jupyter-incubator/sparkmagic
  license: BSD-3-Clause
  license_family: BSD
  summary: Jupyter magics and kernels for working with remote Spark clusters
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - itamarst
    - dbast
    - devstein
